midexamnavarro/urls.py
from django.contrib import admin
from django.urls import path, include
from votes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votes/', include('votes.urls'))
]

votes/urls.py
from django.urls import path
from . import views
app_name = 'votes'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('candidate_create/', views.candidate_create, name='ccreate'),
    path('position_create/', views.position_create, name='pcreate'),
    path('<int:candidate_id>/', views.candidate_detail, name='detail'),
    path('<int:candidate_id>/candidate_update', views.candidate_update, name='candidate_update'),
    path('<int:candidate_id>/vote', views.vote, name='vote')
]

votes/models.py
from django.db import models

# Create your models here.
class Position(models.Model):
    name = models.TextField(max_length=100)
    description = models.TextField(max_length=100)

    def __str__(self):
        return self.name

class Candidate(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    position = models.ForeignKey(Position, on_delete=models.CASCADE, related_name = "position", null=True, blank=True)
    birthdate = models.DateField("Birthdate")
    platform = models.TextField(max_length=100)

    def __str__(self):
        return self.firstname + ", " + self.lastname

class Vote(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name="candidate", null=True, blank=True)
    vote_datetime = models.DateTimeField("Date Voted", auto_now_add=True)

    # def __str__(self):
    #     return self.vote_datetime

votes/forms.py
from django.forms import ModelForm
from votes.models import Candidate, Position, Vote

class CandidateModelForm(ModelForm):
    class Meta:
        model = Candidate
        exclude = ['id']

class PositionModelForm(ModelForm):
    class Meta:
        model = Position
        exclude = ['id']
        
class VoteModelForm(ModelForm):
    class Meta:
        model = Vote
        exclude = ['id']

votes/views.py
from django.shortcuts import render, redirect
from .models import Candidate, Position, Vote
from .forms import CandidateModelForm, VoteModelForm, PositionModelForm

# Create your views here.
def index(request):
    context = {}
    c = Candidate.objects.all().order_by('position')
    context['candidates'] = c
    return render(request, 'index.html', context)

def candidate_create(request):
    context = {}
    context['form'] = CandidateModelForm()
    if request.method == 'POST':
        form = CandidateModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else: 
            return render(request, 'ccreate.html', context)
    else:
        return render(request, 'ccreate.html', context)

def candidate_detail(request, candidate_id):
    context = {}
    context['candidate'] = Candidate.objects.get(id=candidate_id)
    return render(request, 'detail.html', context)

def candidate_update(request, candidate_id):
    context = {}
    post = Candidate.objects.get(id=candidate_id)

    if request.method == 'POST':
        form = CandidateModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('/votes/' + str(candidate_id))
        else:
            context['form']  = form
            return render(request, 'update.html', context)

    else:
        context['form'] = CandidateModelForm(instance=post)
    return render(request, 'update.html', context)

def position_create(request):
    context = {}
    context['form'] = PositionModelForm()
    if request.method == 'POST':
        form = PositionModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else:
            return render(request, 'pcreate.html', context)
    else:
        return render(request, 'pcreate.html', context)

def vote(request, candidate_id):
    print("" + str(candidate_id))
    x = Vote(candidate = Candidate.objects.get(id=candidate_id))
    x.save()
    return redirect('/votes/')

votes/templates/base.html
{% load static %}
<html>
    <head>
        </script>
        <title>
        {% block head %}
            Title Head
        {% endblock head %}
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'votes/materialize/css/materialize.min.css' %}">

        {% block styles %}
        {% endblock styles %}
    </head>
    <body>
    {% block body %}
        Body
    {% endblock body %}
    <script src="{% static 'votes/materialize/js/materialize.min.js' %}"/>
    {% block scripts %}
    {% endblock scripts %}
    </body>
</html>

votes/templates/ccreate.html
{% extends 'base.html' %}
{% block head %}
    Create Candidate Page
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:ccreate' %}" method="POST">
    {% csrf_token %}
    {% for field in form %}
        {{ field.errors }}
        {{ field.label  }} {{ field }}
    {% endfor %}
    <input type="submit" value="Add Candidate">
    </form>
{% endblock body %}

votes/templates/detail.html
{% extends 'base.html' %}

{% block head %}
    Candidate Details Page
{% endblock head %}

{% block body %}
    <div> 
        <h2> {{ candidate.lastname }}, {{ candidate.firstname }} </h2>
            <a href="{% url 'votes:candidate_update' candidate.id %}"><span>Edit</span> </a>
    </div>
    <div class="row"> 
        <small> Position: {{ candidate.position }}</small> 
    </div>
    <div class="row"> 
        <small> Birthdate: {{ candidate.birthdate }}</small>
        <small> {{ candidate.candidate.count}} votes </small>
    </div>
    <div class="row"> 
        <p> {{ candidate.platform }} <p>
    </div>
    <a href='{% url 'votes:vote' candidate.id %}'> <span>VOTE</span> </a>
{% endblock body %}

votes/templates/index.html
{% extends 'base.html' %}
{% block head %}
    List of Candidates
{% endblock head %}
{% block body %}
    {% csrf_token %}
    <ol>
    {% for candidate in candidates %}
            <a href="{% url 'votes:detail' candidate.id %}">
                <div>
                    <h5>{{ candidate.lastname }}, {{candidate.firstname}}</h5>
                    <small> {{ candidate.candidate.count }} votes </small>
                </div>
    {% endfor %}
    </ol>
    <a href="{% url 'votes:ccreate' %}">Add a New Candidate</a><br />
    <a href="{% url 'votes:pcreate' %}">Add a New Position</a>
{% endblock body %}

votes/templates/pcreate.html
{% extends 'base.html' %}
{% block head %}
    Create Position Page
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:pcreate' %}" method="POST">
    {% csrf_token %}
    {% for field in form %}
        {{ field.errors }}
        {{ field.label  }} {{ field }}
    {% endfor %}
    <input type="submit" value="Add Position">
    </form>
{% endblock body %}

votes/templates/update.html
{% extends 'base.html' %}


{% block head %}
    The Update Page
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:candidate_update' form.instance.id %}" method="POST">
        {% csrf_token %}

        <div> 
                <h1> Edit {{ form.lastname.value }}, {{ form.firstname.value }} </h1>
        </div>

             {{ form }}
        <input type="submit" value="Update">
    </form>
{% endblock body %}